[build]
  environment = { NODE_VERSION = "12.0.0" }
  command = "npm run build"
  publish = "dist"
[template.environment]
  KEYSTONE_API = "https://keystone-comments.herokuapp.com/admin/api"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

